# Generated by Django 2.1.1 on 2018-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='My location', max_length=120),
        ),
    ]
